AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Strands Migration - One Piece TCG Customer Service Agent with Secure Secrets Management'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Deployment environment
    
  ProvisionedConcurrency:
    Type: Number
    Default: 2
    Description: Number of provisioned concurrency units

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024
    Runtime: python3.12
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        PYTHONPATH: /var/task:/opt/python

Resources:
  # Lambda Function
  StrandsAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'one-piece-tcg-strands-agent-v2-${Environment}'
      CodeUri: .
      Handler: strands_lambda_handler.handler
      
      # Auto-publish alias for versioning
      AutoPublishAlias: live
      
      Environment:
        Variables:
          # Parameter Store paths - secrets loaded at runtime
          SHOPIFY_URL_PARAM: !Sub '/tcg-agent/${Environment}/shopify/store-url'
          SHOPIFY_ACCESS_TOKEN_PARAM: !Sub '/tcg-agent/${Environment}/shopify/access-token'
          SHOPIFY_STOREFRONT_TOKEN_PARAM: !Sub '/tcg-agent/${Environment}/shopify/storefront-token'
          COMPETITIVE_DECK_SECRET_PARAM: !Sub '/tcg-agent/${Environment}/deck-api/secret'
          COMPETITIVE_DECK_ENDPOINT_PARAM: !Sub '/tcg-agent/${Environment}/deck-api/endpoint'
          LANGFUSE_PUBLIC_KEY_PARAM: !Sub '/tcg-agent/${Environment}/langfuse/public-key'
          LANGFUSE_SECRET_KEY_PARAM: !Sub '/tcg-agent/${Environment}/langfuse/secret-key'
          LANGFUSE_API_URL_PARAM: !Sub '/tcg-agent/${Environment}/langfuse/api-url'
      
      Layers:
        - !Ref StrandsLayer
        - !Ref ShopifyMCPLayer
      
      Policies:
        - Version: '2012-10-17'
          Statement:
            # Parameter Store access for secrets
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: 
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/tcg-agent/${Environment}/*'
            # Bedrock access for LLM calls (all regions)
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:ConverseStream
              Resource: 
                - arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0
                - arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0
                - arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0
                - !Sub 'arn:aws:bedrock:us-east-1:${AWS::AccountId}:inference-profile/us.anthropic.claude-3-5-haiku-20241022-v1:0'
                - !Sub 'arn:aws:bedrock:us-west-2:${AWS::AccountId}:inference-profile/us.anthropic.claude-3-5-haiku-20241022-v1:0'
                - !Sub 'arn:aws:bedrock:us-east-2:${AWS::AccountId}:inference-profile/us.anthropic.claude-3-5-haiku-20241022-v1:0'

  # Function URL (separate resource)
  StrandsAgentFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt StrandsAgentFunction.Arn
      AuthType: NONE
      Cors:
        AllowCredentials: false
        AllowHeaders:
          - content-type
          - x-amz-date
          - authorization
          - x-api-key
        AllowMethods:
          - POST
          - GET
        AllowOrigins:
          - "*"
      InvokeMode: BUFFERED

  # Permission for Function URL
  StrandsAgentFunctionUrlPublicPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StrandsAgentFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  # Lambda Layers
  StrandsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'strands-agents-layer-${Environment}'
      Description: Strands Agents framework and Python dependencies
      ContentUri: layers/strands-layer/strands-layer.zip
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete

  ShopifyMCPLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'shopify-mcp-layer-${Environment}'
      Description: Shopify MCP server for Node.js
      ContentUri: layers/shopify-mcp-layer/shopify-mcp-layer.zip
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete

  # CloudWatch Log Group
  StrandsAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/one-piece-tcg-strands-agent-v2-${Environment}'
      RetentionInDays: 14


Outputs:
  FunctionUrl:
    Description: 'Lambda Function URL for Shopify integration'
    Value: !GetAtt StrandsAgentFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionUrl'
      
  FunctionName:
    Description: 'Lambda Function Name'
    Value: !Ref StrandsAgentFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
      
  FunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt StrandsAgentFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
      
  Environment:
    Description: 'Deployment Environment'
    Value: !Ref Environment
    Export:
      Name: !Sub '${AWS::StackName}-Environment'
